### ISSUE TITLE
Need new pages created

### ISSUE THREAD

**Issue by isensmith** [antonioortegajr/comic-cube#21]
/boxes
/shops
/list
/settings
/boxit
/boxitoptions
/boxitstorechoice
/boxitconfirm

**Comment by antonioortegajr** [comment]
drafts was renamed to boxes.

**Comment by antonioortegajr** [comment]
list was created.

**Comment by antonioortegajr** [comment]
settings was created.

**Comment by antonioortegajr** [comment]
shops was created.

**Comment by antonioortegajr** [comment]
not creating /boxit
/boxitoptions
/boxitstorechoice
/boxitconfirm

at this time.
