### ISSUE TITLE
determine book db schema

### ISSUE THREAD

**Issue by isensmith** [antonioortegajr/comic-cube#5]
how will we organize the data on comic book collections?

**Comment by antonioortegajr** [comment]
Comic book data will have concerns like title, main character, publisher, and possibly more.

**Comment by antonioortegajr** [comment]
The mentioned concerns would also exend to graphic novels and trade paperbacks.

**Comment by isensmith** [comment]
title, publisher, main character/group, series (ie: marvel now, secret wars, death of wolverine), writer(s), artists(s), over-sized issue (ie: special edition issues that are extra long), variant cover, cover artist(s), reprint (y/n, ie: wicdiv did re-prints for second printing of first several issues)

i figure some of this data will no be available from whatever source we use.

**Comment by bauski** [comment]
All of those are nice but let's start with what the feed gives us in the beginning and we can add onto it bit by bit. The feed we will be scraping will be have publisher, title, issue # and dollar. Let's start with that schema. I will create some dummy data that uses this schema.
